#include "graphics.h"
#include<stdio.h> 

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);


// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.
void drawAppState(AppState *state) {
	AppState appState = *state;

	switch(appState.nextState) {
		case SONG_SELECT:
		;
		u16 img1, img2, img3;

		// fillScreenDMA(WHITE);

		img2 = songs[appState.currentSongIndex].previewImage;
		
		if(appState.currentSongIndex == 0) {
			img1 = songs[NUM_SONGS - 1].previewImage;
			img3 = songs[1].previewImage;
		} else if (appState.currentSongIndex == (NUM_SONGS - 1)) {
			img1 = songs[NUM_SONGS - 2].previewImage;
			img3 = songs[0].previewImage;
		} else {
			img1 = songs[appState.currentSongIndex - 1].previewImage;
			img3 = songs[appState.currentSongIndex + 1].previewImage;
		}

		drawRectDMA(15, 45, 50, 50, img1);
		drawRectDMA(80, 30, 80, 80, img2);
		drawRectDMA(175, 45, 50, 50, img3);


		break;


		case SONG_PLAY:
		// fillScreenDMA(BLACK);

		break;


		case SONG_COMPLETE:
		break;

		default:
		break;
	}
}
