#include "graphics.h"
#include<stdio.h> 

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);


// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.

static char shortLivedCharBuffer[20]; 

void drawAppState(AppState *state) {
	AppState appState = *state;

	Song currentSong = songs[appState.currentSongIndex];

	switch(appState.nextState) {
		case SONG_SELECT:
		;

		//Draw the song selection carousell
		u16 img1, img2, img3;

		fillScreenDMA(WHITE);

		img2 = songs[appState.currentSongIndex].previewImage;

		if(appState.currentSongIndex == 0) {
			img1 = songs[NUM_SONGS - 1].previewImage;
			img3 = songs[1].previewImage;
		} else if (appState.currentSongIndex == (NUM_SONGS - 1)) {
			img1 = songs[NUM_SONGS - 2].previewImage;
			img3 = songs[0].previewImage;
		} else {
			img1 = songs[appState.currentSongIndex - 1].previewImage;
			img3 = songs[appState.currentSongIndex + 1].previewImage;
		}

		drawRectDMA(15, 45, 50, 50, img1);
		drawRectDMA(80, 30, 80, 80, img2);
		drawRectDMA(175, 45, 50, 50, img3);


		break;

		case SONG_PLAY_PREP:
		fillScreenDMA(BLACK);
		break;


		case SONG_PLAY:
		;

        //Keep track of how far in the song we are
		int frameProgress = (vBlankCounter - appState.firstFrameOfThisSong);
		int beatProgress = (frameProgress / currentSong.framesPerBeat);
		int framesIntoThisBeat = frameProgress % currentSong.framesPerBeat;

		//int hack... it's 20 x the actual percent
		int beatPercentElapsed = (framesIntoThisBeat * 20) / currentSong.framesPerBeat;

		// DEBUG
		drawRectDMA(0, 0, 150, 20, BLACK);
		char str[25];
		sprintf(str, "percent elapsed: %d", beatPercentElapsed);
		drawString(0, 0, str, WHITE);

		//Draw notes
		int notesY = HIT_Y * beatPercentElapsed;
		if(currentSong.beatmap[beatProgress] & 0x0800) {
			drawRectDMA(5, notesY, NOTE_SIZE, BACKGROUND_REDRAW_HEIGHT, BLACK);
			drawRectDMA(5, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}
		if(currentSong.beatmap[beatProgress] & 0x0400) {

			drawRectDMA(35, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}
		if(currentSong.beatmap[beatProgress] & 0x0200){

			drawRectDMA(65, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}
		if(currentSong.beatmap[beatProgress] & 0x0100){

			drawRectDMA(95, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}
		if(currentSong.beatmap[beatProgress] & 0x0008){

			drawRectDMA(125, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}
		if(currentSong.beatmap[beatProgress] & 0x0004){

			drawRectDMA(155, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}
		if(currentSong.beatmap[beatProgress] & 0x0002){

			drawRectDMA(185, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}
		if(currentSong.beatmap[beatProgress] & 0x0001){

			drawRectDMA(215, notesY, NOTE_SIZE, NOTE_SIZE, RED);
		}




		break;


		case SONG_COMPLETE:
		fillScreenDMA(BLACK);

		//Tell the player how they did!

		drawCenteredString(60, 20, 0, 0, "Song", WHITE);
		drawRectDMA(20, 35, 80, 80, currentSong.previewImage);
		drawCenteredString(60, 140, 0, 0, currentSong.name, WHITE);

		sprintf(shortLivedCharBuffer, "Perfects: %d", appState.score.perfects);
		drawString(130, 20, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Greats: %d", appState.score.greats);
		drawString(130, 50, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Okays: %d", appState.score.oks);
		drawString(130, 80, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Misses: %d", appState.score.misses);
		drawString(130, 110, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Total Score: %d", appState.score.totalScore);
		drawString(130, 140, shortLivedCharBuffer, WHITE);

		break;

		case SONG_COMPLETE_NODRAW:
		break;

		default:
		break;
	}
}
