#include "graphics.h"
#include<stdio.h> 

// TA-TODO: Include any header files for images generated by nin10kit.
// Example for the provided garbage image:
//#include "images/garbage.h"

// TA-TODO: Add any draw/undraw functions for sub-elements of your app here.
// For example, for a snake game, you could have a drawSnake function
// or a drawFood function
//
// e.g.:
// static void drawSnake(Snake* snake);
// static void drawFood(Food* food);


// This function will be used to draw things that might have moved in a frame.
// For example, in a Snake game, draw the snake, the food, the score.


//TODO replace black w background, replace color with img
void drawFallingCircles(int noteIndex, int beatPercentElapsed, volatile u16 color) {
	int notesY = HIT_Y * beatPercentElapsed;
	int scaledNoteSize = ((beatPercentElapsed * NOTE_SIZE) / HIT_Y_MULT);
	int noteBaseOffset = (NOTE_PADDING / 2) + (noteIndex * (NOTE_SIZE + NOTE_PADDING));
	int scaledNoteOffset = ((NOTE_SIZE - scaledNoteSize) / 2);

	drawRectDMA(noteBaseOffset + scaledNoteOffset, notesY - BACKGROUND_REDRAW_HEIGHT, NOTE_SIZE, BACKGROUND_REDRAW_HEIGHT, BLACK);
	drawRectDMA(noteBaseOffset + scaledNoteOffset, notesY, scaledNoteSize, scaledNoteSize, color);
}

//TODO replace color with img.
void drawTapIndicator(int noteIndex, int y, volatile u16 color) {
	drawRectDMA((NOTE_PADDING / 2) + (noteIndex * (NOTE_SIZE + NOTE_PADDING)), y, NOTE_SIZE, NOTE_SIZE, color);
}

//for drawing text & stuff
static char shortLivedCharBuffer[20]; 


void drawAppState(AppState *state) {
	AppState appState = *state;

	Song currentSong = songs[appState.currentSongIndex];

	switch(appState.nextState) {
		case SONG_SELECT:
		;

		//Draw the song selection carousell
		u16 img1, img2, img3;

		fillScreenDMA(WHITE);

		img2 = songs[appState.currentSongIndex].previewImage;

		if(appState.currentSongIndex == 0) {
			img1 = songs[NUM_SONGS - 1].previewImage;
			img3 = songs[1].previewImage;
		} else if (appState.currentSongIndex == (NUM_SONGS - 1)) {
			img1 = songs[NUM_SONGS - 2].previewImage;
			img3 = songs[0].previewImage;
		} else {
			img1 = songs[appState.currentSongIndex - 1].previewImage;
			img3 = songs[appState.currentSongIndex + 1].previewImage;
		}

		drawRectDMA(15, 45, 50, 50, img1);
		drawRectDMA(80, 30, 80, 80, img2);
		drawRectDMA(175, 45, 50, 50, img3);


		break;

		case SONG_PLAY_PREP:
		fillScreenDMA(BLACK);
		break;


		case SONG_PLAY:
		;

        //Keep track of how far in the song we are
		int frameProgress = (vBlankCounter - appState.firstFrameOfThisSong);
		int beatProgress = (frameProgress / currentSong.framesPerBeat);
		int framesIntoThisBeat = frameProgress % currentSong.framesPerBeat;
		//int hack... it's hitymult x the actual percent
		int beatPercentElapsed = (framesIntoThisBeat * HIT_Y_MULT) / currentSong.framesPerBeat;

		// DEBUG
		drawRectDMA(0, 0, 150, 20, BLACK);
		char str[25];
		sprintf(str, "debug: %d", beatPercentElapsed);
		drawString(0, 0, str, WHITE);


		//This is just to have the whole "brief pause after the song". may need to adjust if we want to have background effects going in that time.
		if (beatProgress > currentSong.beatCount) {
			break;
		}


		//Draw in the notes
		foreach(Note *note, notes) {
			if(currentSong.beatmap[beatProgress] & note->mapCode) {
				drawFallingCircles(note->index, beatPercentElapsed, BLUE);
			}

			//clear out a lingering note at the hit circle
			//TODO replace black with background
			if((currentSong.beatmap[beatProgress - 1] & note->mapCode) && (framesIntoThisBeat == 0)) {
				drawRectDMA((NOTE_PADDING / 2) + (note->index * (NOTE_SIZE + NOTE_PADDING)), HIT_Y_ACTUAL - 10, NOTE_SIZE, NOTE_SIZE + 10, BLACK);
			}

			//Draw hit indicators
			if(appState.tapsThisFrame & note->mapCode) {
				drawTapIndicator(note->index, HIT_Y_ACTUAL, RED);
			}
		}


		break;


		case SONG_COMPLETE:
		fillScreenDMA(BLACK);

		//Tell the player how they did!

		drawCenteredString(60, 20, 0, 0, "Song", WHITE);
		drawRectDMA(20, 35, 80, 80, currentSong.previewImage);
		drawCenteredString(60, 140, 0, 0, currentSong.name, WHITE);

		sprintf(shortLivedCharBuffer, "Perfects: %d", appState.score.perfects);
		drawString(140, 20, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Greats: %d", appState.score.greats);
		drawString(140, 50, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Okays: %d", appState.score.oks);
		drawString(140, 80, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Misses: %d", appState.score.misses);
		drawString(140, 110, shortLivedCharBuffer, WHITE);

		sprintf(shortLivedCharBuffer, "Total Score: %d", appState.score.totalScore);
		drawString(110, 130, shortLivedCharBuffer, WHITE);

		break;

		case SONG_COMPLETE_NODRAW:
		break;

		default:
		break;
	}
}
