#include "gba.h"
#include "logic.h"
#include "graphics.h"
// TA-TODO: Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
//#include "images/garbage.h"

#include <stdio.h>
#include <stdlib.h>


int main(void) {
    // TA-TODO: Manipulate REG_DISPCNT here to set Mode 3.
    REG_DISPCNT = MODE3 | BG2_ENABLE;

    GBAState state = START;

    AppState appState;

    // We store the current and previous values of the button input.
    u32 previousButtons = BUTTONS;
    u32 currentButtons = BUTTONS;

    while(1) {
        // Load the current state of the buttons
        currentButtons = BUTTONS;
        // fillScreenDMA(CYAN);

        switch(state) {
            case START:
            // Wait for VBlank
            waitForVBlank();

            // TODO: Draw a spash screen
            fillScreenDMA(CYAN);

            // state = START;
            state = START_NODRAW;
            break;


            case START_NODRAW:
            // Start the app by switching the state to APP_INIT.
            if(GET_KEY(BUTTON_ANY)) {
                state = APP_INIT;
            }
            break;


            case APP_INIT:
            // Initialize the app. Switch to the APP state.
            initializeAppState(&appState);

            // Draw the initial state of the app
            fullDrawAppState(&appState);

            state = SONG_SELECT;
            break;


            //These three states are equivelant from the main render logic's prespective.
            case SONG_SELECT:
            case SONG_PLAY:
            case SONG_COMPLETE:
            // Process the app for one frame, store the next state
            processAppState(&appState, previousButtons, currentButtons);

            // Wait for VBlank before we do any drawing.
            waitForVBlank();

            // Draw the current state
            drawAppState(&appState);

            // Go to the next state as decided by the logic
            state = appState.nextState;
            
            //Fufil requirement "you can restart at any time by pressing select"
            if(GET_KEY(BUTTON_SELECT)) {
                state = START;
            }
            break;
        }

        // Store the current state of the buttons
        previousButtons = currentButtons;
    }

    return 0;
}
