
/**************************************************************
 *	
 *	Bokura, 8 bit, 11025Hz,
 *	1 channel, 652385 bytes/channel
 *	Total Size: 1 * 652385 + 4 (header) = 652429 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Bokura.wav
 *	Time-stamp: Tue Nov 20 22:07:18 2018
 *	
 **************************************************************/

#ifndef __BOKURAH__
#define __BOKURAH__

#define BOKURAFREQ 11025
#define BOKURALEN 652385

extern const unsigned char Bokura[652385];

#endif /* __BOKURAH__ */
