
/**************************************************************
 *	
 *	HitNoise, 8 bit, 44100Hz,
 *	1 channel, 8721 bytes/channel
 *	Total Size: 1 * 8721 + 4 (header) = 8765 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\HitNoise.wav
 *	Time-stamp: Tue Nov 20 22:07:23 2018
 *	
 **************************************************************/

#ifndef __HITNOISEH__
#define __HITNOISEH__

#define HITNOISEFREQ 44100
#define HITNOISELEN 8721

extern const unsigned char HitNoise[8721];

#endif /* __HITNOISEH__ */
