
/**************************************************************
 *	
 *	HitNoise, 8 bit, 11025Hz,
 *	1 channel, 2180 bytes/channel
 *	Total Size: 1 * 2180 + 4 (header) = 2224 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\HitNoise.wav
 *	Time-stamp: Tue Nov 20 18:57:28 2018
 *	
 **************************************************************/

#ifndef __HITNOISEH__
#define __HITNOISEH__

#define HITNOISEFREQ 11025
#define HITNOISELEN 2180

extern const unsigned char HitNoise[2180];

#endif /* __HITNOISEH__ */
