
/**************************************************************
 *	
 *	Koi, 8 bit, 11025Hz,
 *	2 channel, 692868 bytes/channel
 *	Total Size: 2 * 692868 + 4 (header) = 1385780 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Koi.wav
 *	Time-stamp: Tue Nov 20 18:57:31 2018
 *	
 **************************************************************/

#ifndef __KOIH__
#define __KOIH__

#define KOIFREQ 11025
#define KOILEN 692868

extern const unsigned char Koi_c1[692868];
extern const unsigned char Koi_c2[692868];

#endif /* __KOIH__ */
