
/**************************************************************
 *	
 *	Koi, 8 bit, 11025Hz,
 *	1 channel, 692868 bytes/channel
 *	Total Size: 1 * 692868 + 4 (header) = 692912 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Koi.wav
 *	Time-stamp: Tue Nov 20 22:07:29 2018
 *	
 **************************************************************/

#ifndef __KOIH__
#define __KOIH__

#define KOIFREQ 11025
#define KOILEN 692868

extern const unsigned char Koi[692868];

#endif /* __KOIH__ */
