
/**************************************************************
 *	
 *	Natsu, 8 bit, 11025Hz,
 *	1 channel, 663885 bytes/channel
 *	Total Size: 1 * 663885 + 4 (header) = 663929 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Natsu.wav
 *	Time-stamp: Tue Nov 20 22:07:33 2018
 *	
 **************************************************************/

#ifndef __NATSUH__
#define __NATSUH__

#define NATSUFREQ 11025
#define NATSULEN 663885

extern const unsigned char Natsu[663885];

#endif /* __NATSUH__ */
