
/**************************************************************
 *	
 *	Snow, 8 bit, 11025Hz,
 *	1 channel, 660408 bytes/channel
 *	Total Size: 1 * 660408 + 4 (header) = 660452 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Snow.wav
 *	Time-stamp: Tue Nov 20 22:07:36 2018
 *	
 **************************************************************/

#ifndef __SNOWH__
#define __SNOWH__

#define SNOWFREQ 11025
#define SNOWLEN 660408

extern const unsigned char Snow[660408];

#endif /* __SNOWH__ */
