
/**************************************************************
 *	
 *	Snow, 8 bit, 11025Hz,
 *	2 channel, 660408 bytes/channel
 *	Total Size: 2 * 660408 + 4 (header) = 1320860 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Snow.wav
 *	Time-stamp: Tue Nov 20 18:57:37 2018
 *	
 **************************************************************/

#ifndef __SNOWH__
#define __SNOWH__

#define SNOWFREQ 11025
#define SNOWLEN 660408

extern const unsigned char Snow_c1[660408];
extern const unsigned char Snow_c2[660408];

#endif /* __SNOWH__ */
