
/**************************************************************
 *	
 *	Step, 8 bit, 11025Hz,
 *	2 channel, 668856 bytes/channel
 *	Total Size: 2 * 668856 + 4 (header) = 1337756 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Step.wav
 *	Time-stamp: Tue Nov 20 18:57:41 2018
 *	
 **************************************************************/

#ifndef __STEPH__
#define __STEPH__

#define STEPFREQ 11025
#define STEPLEN 668856

extern const unsigned char Step_c1[668856];
extern const unsigned char Step_c2[668856];

#endif /* __STEPH__ */
