
/**************************************************************
 *	
 *	Step, 8 bit, 11025Hz,
 *	1 channel, 668856 bytes/channel
 *	Total Size: 1 * 668856 + 4 (header) = 668900 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Step.wav
 *	Time-stamp: Tue Nov 20 22:07:40 2018
 *	
 **************************************************************/

#ifndef __STEPH__
#define __STEPH__

#define STEPFREQ 11025
#define STEPLEN 668856

extern const unsigned char Step[668856];

#endif /* __STEPH__ */
