
/**************************************************************
 *	
 *	Victory, 8 bit, 11025Hz,
 *	1 channel, 537971 bytes/channel
 *	Total Size: 1 * 537971 + 4 (header) = 538015 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Victory.wav
 *	Time-stamp: Tue Nov 20 23:31:45 2018
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 537971

extern const unsigned char Victory[537971];

#endif /* __VICTORYH__ */
