
/**************************************************************
 *	
 *	Victory, 8 bit, 11025Hz,
 *	1 channel, 41846 bytes/channel
 *	Total Size: 1 * 41846 + 4 (header) = 41890 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	D:\Computer Science\C\GBARhythmGame\songs\Victory.wav
 *	Time-stamp: Tue Nov 20 22:07:53 2018
 *	
 **************************************************************/

#ifndef __VICTORYH__
#define __VICTORYH__

#define VICTORYFREQ 11025
#define VICTORYLEN 41846

extern const unsigned char Victory[41846];

#endif /* __VICTORYH__ */
